services:

  app:
    container_name: app_container
    build:
      context: ../../../../
      dockerfile: ops-tools/docker/images/app-3/Dockerfile
    restart: no
    ports:
      - "8888:8080"
    networks:
      - docker-practice-net
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
    command: sh -c "java -jar app.jar"


  postgres:
    container_name: postgres_container
    image: postgres:12.20-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
      PGDATA: data/postgres
    volumes:
      - ../../../../data/postgres:/data/postgres
      - ../../../../data/dump:/db-dump
    ports:
      - "5432:5432"
    networks:
      - docker-practice-net

  redis:
    image: redis:alpine3.20
    container_name: redis_container
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - docker-practice-net

networks:
  docker-practice-net:
